version: '3'
services:
  app:
    tty: true
    build: ./
    ports:
      - "9000:9000"
      - "9999:9999"
      - "8888:8888"
    volumes:
    - ".:/home/sebis/projects/akrec"
    depends_on:
      - mongo
      - mongo-seed
    links:
      - mongo:mongo
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    links:
      - mongo:mongo
  mongo:
    image: 'mongo:3.6.2'
    ports:
        - 27017:27017