version: '3'
services:
  akre:
    image: 'sebischair/amelie:akre'
    ports:
      - "9000:9000"
    depends_on:
      - docclustering
      - docclassification
      - syncpipes-server
    links:
      - mongo:mongo
      - docclustering:docclustering
      - docclassification:docclassification
      - syncpipes-server:syncpipes-server
  amelie:
    image: 'sebischair/amelie:amelietor'
    ports:
      - "8080:3001"
      - "8081:3002"
    depends_on:
      - akre
  syncpipes-client:
    image: 'sebischair/amelie:syncpipes-client'
    depends_on:
      - syncpipes-server
    ports:
      - "3011:80"
  syncpipes-server:
    image: 'sebischair/amelie:syncpipes-server'
    ports:
      - "3010:3010"
    depends_on:
      - mongoforamelie
      - rabbit
    links:
      - mongo:mongo
      - rabbit:rabbit
    environment:
      SYNCPIPES_PORT: 3010
      SYNCPIPES_MONGO_HOST: 'mongo'
      SYNCPIPES_MONGO_URL: 'mongodb://mongo/syncpipes'
      SYNCPIPES_RABBIT_HOST: rabbit
      SYNCPIPES_RABBIT_PORT: 5672
      SYNCPIPES_RABBIT_USER: guest
      SYNCPIPES_RABBIT_PASSWORD: guest
      SYNCPIPES_RABBIT_VHOST: '/'
  docclassification:
    image: 'sebischair/amelie:docclassification'
    ports:
      - "3005:3005"
    depends_on:
      - mongoforamelie
    links:
      - mongo:mongo
  docclustering:
    image: 'sebischair/amelie:docclustering'
    ports:
      - "3006:3006"
    depends_on:
      - mongoforamelie
    links:
      - mongo:mongo
  mongoforamelie:
    image: 'sebischair/amelie:mongoforamelie'
    depends_on:
      - mongo
    links:
      - mongo:mongo
  mongo:
    image: 'mongo:3.6.2'
    ports:
        - 27017:27017
  rabbit:
    image: rabbitmq:management
    ports:
      - "15671:15671"
      - "15672:15672" # management gui
      - "25672:25672"
      - "5672:5672"
      - "5671:5671"
      - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest