version: '3'
services:
  akre:
    tty: true
    build: ./
    ports:
      - "9000:9000"
    depends_on:
      - mongoforamelie
    links:
      - mongo:mongo
  mongoforamelie:
    image: 'sebischair/amelie:mongoforamelie'
    depends_on:
      - mongo
    links:
      - mongo:mongo
  mongo:
    image: 'mongo:3.6.2'
    ports:
        - 27017:27017